### ISSUE TITLE
No data volumes or claims are generated

### ISSUE THREAD

**Issue by Happyman0815** [whs-dot-hk/kubernetes-nifi-refined#1]
I followed all the steps and Nifi is running well but it does not store templates or the current workflow in volumes. 

It seems that not data volumes or Persistent Volume Claims are generated or used.

I am working on a Windows 10 environment.

**Comment by whs-dot-hk** [comment]
Hi, are you using AKS?

**Comment by Happyman0815** [comment]
I use the Kubernetes integrated in Docker Desktop (Edge) for Windows: 

https://hub.docker.com/editions/community/docker-ce-desktop-windows  

Runs on a Microsoft Windows [Version 10.0.17763.253] host PC.

**Comment by whs-dot-hk** [comment]
Do you mean minikube?

**Comment by Happyman0815** [comment]
> Docker Desktop for Windows 18.06.0-ce-win70 CE includes a standalone Kubernetes server and client, as well as Docker CLI integration. The Kubernetes server runs locally within your Docker instance, is not configurable, and is a single-node cluster.
> The Kubernetes server runs within a Docker container on your local system, and is only for local testing. When Kubernetes support is enabled, you can deploy your workloads, in parallel, on Kubernetes, Swarm, and as standalone containers. Enabling or disabling the Kubernetes server does not affect your other workloads.

Source: https://docs.docker.com/docker-for-windows/kubernetes/

I think it is not Minicube.

**Comment by whs-dot-hk** [comment]
How about running
```
$ kubectl delete -f https://raw.githubusercontent.com/whs-dot-hk/kubernetes-nifi-refined/master/nifi.yaml
```

```
# nifi-statefulset.yaml
apiVersion: v1
kind: Service
metadata:
  name: nifi-headless
  labels:
    app: nifi
spec:
  ports:
  - port: 8080
    name: http
  clusterIP: None
  selector:
    app: nifi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
spec:
  selector:
    matchLabels:
      app: nifi
      tier: backend
      track: stable
  serviceName: nifi-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: nifi
        tier: backend
        track: stable
    spec:
      containers:
        - name: nifi
          image: whshk/nifi:latest
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: nifi-data
              mountPath: /opt/nifi/nifi-current/conf
              subPath: conf
            - name: nifi-data
              mountPath: /opt/nifi/nifi-current/logs
              subPath: logs
            - name: nifi-data
              mountPath: /opt/nifi/nifi-current/database_repository
              subPath: database_repository
            - name: nifi-data
              mountPath: /opt/nifi/nifi-current/flowfile_repository
              subPath: flowfile_repository
            - name: nifi-data
              mountPath: /opt/nifi/nifi-current/content_repository
              subPath: content_repository
            - name: nifi-data
              mountPath: /opt/nifi/nifi-current/provenance_repository
              subPath: provenance_repository
            - name: nifi-data
              mountPath: /opt/nifi/nifi-current/state
              subPath: state
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: nifi-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: ""
        resources:
          requests:
storage: 10Gi
```

```
$ kubectl create -f nifi-statefulset.yaml
```

Does it work for you? Please report back.
